version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mcom_loyalty_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nov52002#
      POSTGRES_DB: McomLoyalty
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
